# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12.18
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - test:
          name: Test
          command: yarn test
  deploy:
    steps:
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy
          command: |
            git config --global user.name "Circle CI"
            git config --global user.email "<>"
            git add -A
            git commit -m "[ci skip] Deploy by CI"
            git push -f https://github.com/ikarostech/HPADesign.git master:master
            echo "deploy completed"
workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
