# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.18
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy
          command: |
            if [ "$(git status --porcelain | wc -l | xargs)" -eq 0 ]; then
              echo "Not exist deploying contents."
              exit 0
            fi

            git config --global user.name "Circle CI"
            git config --global user.email "<>"
            git add -A
            git commit -m "[ci skip] Deploy by CI"

            git push -f $(git config --get remote.origin.url) master:master > /dev/null/ 2>&1

            echo "Deploy a site!"

            cd -